<h1>Numpy<h1>


<h3>1.1 ndarray</h3>

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([ [1, 2, 3],
                     [2, 3, 4] ])
print('array2 type:', type(array2))
print('array array 형태:', array2.shape)

array3 = np.array([ [1, 2, 3] ])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1: {:0}차원, array2: {:1} 차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2 차원, array3:  2차원


<h3>1.2 dtype</h3>

In [2]:
import numpy as np

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


<h3>1.3 astype('string')</h3>

In [3]:
import numpy as np

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


<h3>1.4 arange(), zeros(), ones()</h3>

In [4]:
import numpy as np

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [6]:
import numpy as np

zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


<h3>1.5 reshape()</h3>

** reshape() Error<br>
    - reshape()가 지정된 사이즈로 변경이 불가능 할 때 에러 발생

In [ ]:
import numpy as np

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# --------- Value Error ---------

array1.reshape(4,3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

<h4>1.5.1 reshape example (-1)값 적용</h4>

[result]

array1 : 1차원 ndarray, 0~9의 데이터<br>

array2 : row(-1), column(5)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- array1과 호환 가능한 2차원 ndarray로 변환<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- array1의 데이터를 column에 맞게 row를 변경<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 2x5형태로 변경

array3 : 5x2 형태로 변경

In [12]:
import numpy as np

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

# ------- reshape() Error -------
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


ValueError: cannot reshape array of size 10 into shape (4)

** reshape(-1, 1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 원본 ndarray은 2차원으로, 여러개의 row를 가지되 반드시 1개의 column을 가진 ndarray로 변환<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 여러개의 numpy ndarray는 stack이나 concat으로 결합될 때 ndarray의 형태를 통일해 사용

<h4>1.5.2 tolist()</h4>
 - 리스트 자료형으로 변환 (시각적으로 이해하기 쉬움)

In [ ]:
import numpy as np

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2)) 
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


<h3>1.6 Indexing</h3>

1) 특정 데이터만 추출 : 지정된 인덱스 값의 데이터 반환

2) slicing : 연속된 index상의 ndarray를 추출하는 방식<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 시작 인덱스에서 종료 인덱스 -1에 위치한 ndarray 반환<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ex) 1:5 라면 시작 인덱스 1 부터 종료 인덱스 4까지의 ndarray 반환

3) Fancy Indexing : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 존재하는 ndarray 반환

4) Boolean Indexing : True/False값 인덱싱 집합을 기반으로 Truew에 해당하는 ndarray 반환

<h4>1.6.1 단일 값 추출</h4>

- ndarray 객체에 해당하는 위치의 index값을 [] 안에 기입<br>

- 인덱스에 마이너스 기호 입력시 맨 뒤에서 부터 데이터 추출 가능


In [ ]:
import numpy as np

# 1~9까지의 1차원 ndarray
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작 / array1[2]는 index(3)을 의미
value = array1[2]
print('value:', value)
print(type(value))

# 마이너스 기호 사용
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 2번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 2번째 값: 8


<h5>(1) 단일 인덱스를 이용한 ndarray 내 데이터 수정</h5>

In [16]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


<h5>(2) 다차원 ndarray에서 단일 값 추출</h5>

- 2차원의 경우 (,) 콤마로 분리된 row와 column 위치의 인덱스를 통해 접급
- 2차원과 3차원에서의 단일 값 추출 방법이 비슷

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;** axis0 = row0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;** axis1 = column0<br>

In [17]:
import numpy as np

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


<h4>1.6.2 Slicing</h4>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ':' 기호를 아용해 연속되는 데이터를 슬라이싱해 추출<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ndarray 타입<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 형태 : [시작인덱스 : 종료인덱스]<br>

In [1]:
import numpy as np

array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


** 슬라이싱 기호 생략

(1) ':' 기호 앞에 시작 인덱스 생략 => 처음 인덱스 0으로 간주<br>
(2) ':' 기호 뒤에 종료 인덱스 생략 => 맨 뒤 인덱스를 간주<br>
(3) ':' 기호 앞, 뒤에 시작, 종료 인덱스 생략 => 맨 처음과 끝 인덱스 간주<br>

In [1]:
import numpy as np
array1 = np.arange(start=1, stop=10)
# [:3] - 0부터 3번 인덱스 전 까지 추출
array4 = array1[:3] 
print(array4)

# 3번 인덱스 부터 추출
array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


** 2차원 ndarray의 슬라이싱
 - (,) 콤마 row와 column 인덱스를 나눔

In [3]:
import numpy as np
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, 0:3])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


** 2차원 ndarray에서 뒤에 오는 인덱스를 생략하면 1차원 ndarray를 반환<br>

&nbsp;&nbsp;&nbsp;- 반환값 : row축(axis0)의 첫번째 row ndarray반환

In [5]:
import numpy as np
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shap:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shap: (3,)


<h4>1.6.3 Fancing Indexing</h4>

- 리스트나 ndarray로 인덱스 집합 지정 시, 해당 위치의 ndarray 반환

In [7]:
import numpy as np

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[ [0, 1], 2 ]
print('array2d[ [0, 1], 2] =>', array3.tolist())

array4 = array2d[ [0, 1], 0:2 ]
print('array2d[ [0, 1], 0:2] =>', array4.tolist())

array5 = array2d[ [0, 1] ]
print('array2d[ [0, 1] ] =>', array5.tolist())



array2d[ [0, 1], 2] => [3, 6]
array2d[ [0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[ [0, 1] ] => [[1, 2, 3], [4, 5, 6]]


<h4>1.6.4 Boolean Indexing</h4>

- 조건 필링과 검색을 동시에 사용할 수 있음
- 간단하게 사용 가능
- ndarray의 인덱스를 지정하는 [] 안에 조건문을 그대로 기재

In [4]:
import numpy as np
# 조건: 데이터가 5보다 큰 수 출력
# []안에 array1d > 5 Boolean Indexing 적용
array1d = np.arange(start=1, stop=10)

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

print('--------------------------------------------')

print(array1d > 5)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]
--------------------------------------------
[False False False False False  True  True  True  True]


<h5>(1) Boolean Index Filtering</h5>

- 위와 동일한 Boolean ndarray를 생성한 후 array1d[] 안에 인덱스로 입력 시

In [6]:
import numpy as np

array1d = np.arange(start=1, stop=10)
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]

print('Filtered result (Boolean indexing):', array3)

Filtered result (Boolean indexing): [6 7 8 9]


** 직접 인덱스 집합을 만들어 대입했을 경우

In [7]:
import numpy as np

indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링한 결과 :', array4)

일반 인덱스로 필터링한 결과 : [6 7 8 9]


<h5>(2) Boolean Indexing 동작 스텝</h5>

- 1) array1d > 5 와 같이 필터링 조건을 []에 기재
- 2) False값은 무시하고 True값에 해당하는 인덱스값만 저장<br>
&nbsp;&nbsp;&nbsp;&nbsp;** 유의: True값 자체인 1을 지정하는 것이 아닌 True값을 가진 Index를 저장
- 3) 저장된 인덱스 데이터 세트로 ndarray 조회

<h4></h4>

<h3>1.7 sort() & argsort()</h3><br>
- 행열을 정렬하는 방법 : np.sort(), ndarray.sort()<br>
- 정렬된 행열의 인덱스 반환 방법: argsort()

<h4>1.7.1 행렬 정렬</h4>
- np.sort() : 원 행렬은 유지한 채 원 행렬에서 정렬된 행렬을 반환<br>
- ndarray.sort() : 원 행렬 자체를 정렬, 반환값 = None

In [10]:
import numpy as np

org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

print('--------------------------------------')

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
--------------------------------------
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
