<h1>scikit-learn</h1>
- 프레임워크, API제공

<h3>3.1 분류 (Classification)</h3>
- 지도학습(Aupervised learning) 방법 중 하나

<h5>** 지도학습</h5>

- 다양한 피처와 분류 결정값인 레이블(Lable) 데이터로 모델을 한습한 후, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측<br>

- 먕확한 정답이 주어진 데이터 先학습， 後 미지의 정답 예측

<h5>사이킷런 모듈</h5>

(1) sklearn.datasets
- 사이킷런 자체 제공 데이터 세트 생성 모듈

(2) sklearn.tree
- 트리기반 ML 알고리즘

(3) sklearn.model_selection
- 학습 데이터, 검증 데이터 통칭
- 하이퍼 파라미터를 통해 머신러닝 알고리즘의 성능 튜닝

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df.head(3)


iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

<h5>▲ Result </h5>

(1) feature
- sepal length
- sepal width
- petal length
- petal width

(2) label
- 0 : Setosa 품종
- 1 : versicolor 품종
- 2 : verginica 품종

<h4>학습용 데이터 및 테스트용 데이터 분리</h4>

- 학습 데이터로 학습된 모델의 성능 평가를 위해 테스트 데이터 세트 필요
- train_test_split()

(1) train_test_split()
- 학습 데이터와 테스트 데이터를 test_size 파라미터 입력값의 비율로 분할


In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)



iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


feature
- iris_data

lable
- iris_lable

test data set 비율
- test_size = 0.2

난수 발생 값 (호출 마다 같은 학습/테스트 용 데이터 세트 생성을 위한)<br>
- random_state

** train_test_split() 호출 시 무작위로 데이터를 분리하므로 random_state() 지정 필요<br>

** DecisionTreeClassifier()
- 의사결정 트리 클래스
- random_state= 지정 
- 학습/예측 결과 출력
- fit() : 학습용 피처 데이터 속성과 결정 값 데이터 세트 입력 


** fit()
- 모델을 학습하는 단계 (피처와 레이블로)

** predict()
- 학습이 끝난 모델이 답을 내는 단계

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)

# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(x_train, y_train)

# 학습 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(x_test)

from sklearn.metrics import accuracy_score
print('예측 정확도: {0: 4F}'.format(accuracy_score(y_test, pred)))

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']
예측 정확도:  0.933333


** 정확도 측정

- accuracy_acore()
- 실제 데이터 세트, 예측 레이블 데이터 세트 순으로 입력

** 분류 예측 프로세스

(1) 데이터 세트 분리 : 학습/테스트 데이터 분리<br>
(2) 모델 학습 : 학습 데이터 기반으로 모델 학습<br>
(3) 예측 수행 : 학습된 ML 모델로 테스트 데이터의 분류 예측<br>
(4) 평가 : 예측된 결과값, 테스트 데이터의 실제 결과값 비교 후 모델 성능 평가

<h3>3.2 사이킷런 기반 프레임워크</h3>

<h4>3.2.1 Estimator 이해 및 fit(), predict()</h4>

- fit() : ML 모델 학습
- predict() : 학습된 모델의 예측
- 지도학습 : 분류(Classifier) / 회귀(Regressor) 클래스에서 fit(), predict()으로 간단하게 학습 및 예측 결과 반환 가능
- Estimator 클래스 = 분류(Classifier) + 회귀(Regressor)


- cross_val_score() : evaluation 함수
- GridSearchCV : 파라미터 튜닝
- cross_val_score(), GridSearchCV.fit() : Estimator의 fit(), predict()를 호출해 평가 및 파라미터 튜닝 수행


<h5>** 비지도 학습에서의 fit(), transform() 사용법</h5>

- 비지도학습 : 차원 축소 / 클러스터링 / 피처 추출(Feature Extraction) 
- fit() : 비지도 학습 및 피처 추출에서 fit() 사용시 압력데이터의 형태에 맞춰 데이터를 변환해주기 위해 사전 구조를 맞추는 작업 진행
- transform() : 차원 변환, 클러스터링, 피처 추출 등 실제 작업 진행

- fit_transform() : fit()과 transform()의 결합물<br>
    => fit()과 transform()을 별도로 호출하지 않아도 됨





<h4>3.2.2 사이킷런의 주요 모듈</h4>


<h5>(1) 예제 데이터</h5>

- sklearn.datasets : 내장돤 예제 제공  데이터 세트

<h5>(2) 피처 처리</h5>

- sklearn.preprocessing<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 데이터 전처리에 필요한 가공 기능 (문자열을 숫자형 코드값으로 인코딩, 정규화, 스케일링 등)

- sklearn.feature_selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 일고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행 기능 제공

- sklearn.feature_extraction<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트, 이미지 데이터의 벡터화된 피처를 추출시 사용<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트 데이터 내 Count Vectorizer, TF-IDF Vectorizer 생산 기능 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트 데이터 피처 추출 : sklearn.feature_extraction.text<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 이미지 데이터 피처 추출 : sklearn.feature_extraction.image<br>

<h5>(3) 피처 처리 & 차원 축소</h5>

- sklearn.decomposition<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 차원 축소 관련 알고리즘 지원 모듈 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> PCA, NMF, Truncated SVD 등을 이용해 차원 축소<br>

<h5>(4) 데이터 분리, 검증 & 파라미터 튜닝</h5>

- sklearn.model_selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 교차 검증을 위한 학습/테스트 용 분리, 그리드 서치로 최적의 파라미터 추출 등 API 제공<br>

<h5>(5) 평가</h5>

- sklearn.metric<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 분류, 회귀, 클러스터링, 페어와이즈(Pairwise)에 대한 다양한 성능 측정 방법<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> Accuracy, Precsion, Recal, ROC-AUC, RMSE 제공<br>

<h5>(6) ML 알고리즘</h5>

- sklearn.ensemble<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 앙상블 알고리즘 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 제공<br>

- sklearn.linear_model<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 선형회귀, 릿지(Ridge), 라쏘(Lasso), 로지스틱 회귀 등 회귀 관련 알고리즘 지원<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> SGD(Stochastic Gradient Descent) 알고리즘 제공<br>

- sklearn.naive_bayes<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 나이브 베이즈 알고리즘 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 기우시안 NB, 다항분포 NB 제공<br>

- sklearn.neighbors<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 최근접 이웃 알고리즘, K-NN<br>

- sklearn.svm<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 서포트 벡터 머신 제공<br>

- sklearn.tree<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 의사결정 트리 제공<br>

- sklearn.cluster<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 비지도 클러스터링 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> K-평균, 계층형, DBSCAN<br>

<h5>(7) 유틸리티</h5>

- sklearn.pipeline<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 피처 처리 등 변환, ML 알고리즘 학습, 예측 등을 함께 묶어 실행 가능한 유틸리티 제공<br>

<h4>3.2.3 내장돤 예제 데이터 세트</h4>
- fetch : 데이터 크기가 커 인터넷에서 다운 받아 사용

<h5>** 표본 데이터 생성기</h5>

(1) 분류<br>
- datasets.make_classifications()<br>
    => 분류를 위한 데이터 세트 생성<br>
    => 높은 상관도, 불필요한 속성 등 노이즈 효과를 위한 데이터 무작위로 생성<br>

(2) 클러스터링<br>
- datasets.make_classifications()<br>
    => 클러스터링를 위한 데이터 세트 무작위 생성<br>
    => 군집 지정 개수에 따라 여러 가지 클러스터링을 위한 데이터 무작위로 생성<br>

<h5>** 내장 데이터 구성</h5>
- 딕셔너리 형태<br>
- 키 : data, target, target_name, feature_names, DESCR로 구성<br>

(1) 넘파이 배열(ndarray)<br>
&nbsp;&nbsp;&nbsp;=> data : 피처의 데이터 세트 <br>
&nbsp;&nbsp;&nbsp;=> target : 분류 시 레이블 값 / 회귀 시 숫자 결과값 데이터 세트<br>

(2) 넘파이 배열(ndarray) & 파이썬 list<br>
&nbsp;&nbsp;&nbsp;=> target_name : 개별 레이블 이름<br>
&nbsp;&nbsp;&nbsp;=> feature_names : 피처 명<br>

(3) String 타입<br>
&nbsp;&nbsp;&nbsp;=> DESCR : 데이터 세트 설명 및 각 피처의 설명<br>



In [6]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


** bunch
- 파이썬 딕셔너리 형태와 유사 / 딕셔너리 형태의 값 반환

In [7]:
from sklearn.datasets import load_iris

iris_data = load_iris()
keys = iris_data.keys()

print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [9]:
from sklearn.datasets import load_iris

iris_data = load_iris()
keys = iris_data.keys()

print('\n feature_names의 type:', type(iris_data.feature_names))
print('\n feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('\n target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n data의 type:', type(iris_data.target))
print('data 의 shape:', iris_data.target.shape)
print(iris_data.target)



 feature_names의 type: <class 'list'>

 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>

 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 

<h3>3.3 Model Selection 모듈 소개</h3>

- 학습 / 테스트 데이터 분리
- 교차 검증 분할 및 평가
- Estimator의 하이퍼 파라미터 튜닝

<h4>3.3.1 학습/테스트 데이터 분리 - train_test_split()</h4>

In [11]:
# 학습과 예측을 동일 데이터 세트로 진행 예제

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
df_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
df_clf.fit(train_data, train_label)

# 학습 데이터 세트로 예측 수행
pred = df_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))


예측 정확도: 1.0


** 학습과 예측을 동일 데이터 세트로 진행 예제 <br>
결과 : 정확도 = 100%<br>
    => 이미 학습한 데이터 세트를 기반으로 예측 진행<br>
    => 오류 발생<br>

해결법 :<br>
    => 예측 수행 데이터 세트 = 예측 전용 데이터 세트여야 함<br>
    => train_test_split() 사용해 학습/테스트 데이터 분리


train_test_split() 파라미터 입력

- test_size<br>
    => 전체 데이터에서 테스트 데이터 세트 크기 얼마로 샘플링 할 것인지 결정<br>
    => 디폴 값 : 0.25 == 25%<br>

- train_size<br>
    => 전체 데이터에서 학습 데이터 세트 크기를 얼마로 샘플링할 것인지 결정<br>
    => 자주 사용 x<br>
    => test_size_parameter를 주로 사용<br>

- shuffle<br>
    => 데이터를 분리하기 전 데이터를 미리 섞을지 결정 <br>
    => 데이터를 분산시켜 좀 더 효율적인 학습 및 테스트 데이터 세트를 만드는데 사용
    => 디폴트 값 : True<br>

- random_state<br>
    => 호출할 때 마다 동일한 학습/테스트 데이터 세트 생성을 위해 주어지는 난수 값<br>
    => train_test_split() 사용 시 무작위로 데이터 생성 됨 따라서 동일한 학습/테스트 데이터 세트 생성을 위해 random_state 지정 필요<br>


In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

df_clf = DecisionTreeClassifier()
iris_data = load_iris()

x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, 
                                                    test_size=0.3, random_state=121)

df_clf.fit(x_train, y_train)
pred = df_clf.predict(x_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))


예측 정확도: 0.9556


<h3>3.4 교차 검증</h3>

** 교차 검증이 필요한 이유<br>
- 과적합(Overfitting) : 학습 데이터에만 과도하게 최적화되어 다른 데이터로 실제 예측을 진행 할 때 예측 성능이 과도하게 떨어짐 <br>

** 교차 검증
- 데이터 편증 : ML 알고리즘에서 최적의 동작을 위해 데이터를 선별해 학습할 셩우 실제 데이터 양식과 큰 차이가 발생하며 성능저하로 이어지게 됨 <br>
- 데이터 편증을 막기 위해 수 많은 학습과 검증 세트에서 알고리즘 학습과 평가를 수행<br>
- 평가 결과에 따라 하이퍼 파라미터 튜닝 등의 모델 최적화를 쉽게 진행 할 수 있게 됨<br>

** ML 모델의 성능 평가<br>
- 교차검증을 기반으로 1차 평가 진행<br>
- 최종적으로 테스트 데이터 세트에 적용해 평가 진행<br>
- ML에 사용되는 테스트 데이터를 세분화해 학습/검증/테스트 데이터 세트로 나눌 수 있음<br>
- 테스트 데이터 세트 외 별도의 검증 데이터 세트를 사용해 최종 평가 이전에 학습된 모델을 다양하게 평가하는데 사용<br>

<h4>3.4.1 K 폴드 교차검증</h4>

- KFold 모델<br>
- StratifieldKFold 모델<br>
- 가장 보편적으로 사용되는 교차 검증<br>
- K개의 데이터 폴드 세트를 생성 후 K번 만큼 각 폴드 세트에 학습/검증 평가를 반복적으로 수행<br>


** K 폴드 교차 검증 예시(5폴드 교차 검증)<br>
- 5개의 폴드된 학습/검증 데이터 세트를 변경하며 생성 -> 5번 평가 수행<br>
- 예측성능 평가<br>
- 데이터 세트를 K등분(5등분)하여 아래의 과정 진행<br>
    ✦ 1번째 ==> 1~4: 학습 / 5:검증<br>
    ✦ 2번째 ==> 1~3: 학습 / 4: 검증 / 5: 학습<br>
    ✦ 3번째 ==> 1~2: 학습 / 3: 검증 / 4~5: 학습<br>
    ✦ 4번째 ==> 1: 학습 / 2: 검증 / 3~5: 학습<br>
    ✦ 5번째 ==> 1: 검증 / 2~5: 학습<br>
- K폴드 평과 결과 : 5개의 예측평가 진행 후 평균값을 


In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
df_clf = DecisionTreeClassifier(random_state=156)

#  5개의 폴드 세트로 분리하는 KFold 객체 & 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris  # 추가
import numpy as np

iris = load_iris()  # iris 데이터셋 로드
features = iris.data
label = iris.target
df_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []

n_iter = 0

# KFold 개ㄱ체의 split()를 호출하면 폴드별 학습/검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    # kfold.split()로 반환된 인덱스를 이용해 학습/검증용 테스트 데이터 추출
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    df_clf.fit(x_train, y_train)
    pred = df_clf.predict(x_test)
    n_iter += 1
    
    # 반복시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))



#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


<h4>3.4.2 Stratified K폴드</h4>

** 불균형한 분포도를 가진 레이블 데이터 집합<br>
- 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한쪽으로 치우쳐지는 것<br>

- 불균형한(imbalanced)분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K폴드 방식<br>
- K폴드가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결<br>
 => 원본 데이터의 레이블 분포를 우선 고려 후 이 분포와 동일하게 학습과 검증 데이터 세트를 분배

In [12]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [14]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64


KFold(n_splits=3)<br>
학습/검증 레이블이 교차 검증시 3개의 폴드 세트로 만들어짐<br>

**결과

학습레이블에서 1과 2의 값이 각각 50개 추출<br>
검증데이터에서 0값이 50개 추출<br>

=> 학습 모델은 절대 0을 예측 할 수 없음<br>
=> 교차 검증 데이터 세트 분할 시 검증 에측 정화도 = 0임

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter = 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print('## 교차 검증{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증1
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증1
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


StratifiedKFold는 레이블 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에 split() 메서드에 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트도 필요

ex) for train_index, test_index in skf.split(iris_df, iris_df['label']):<br>
<br>
<br>
** 결과

- 학습 레이블과 검증 레이블 데이터 값의 분포도가 거의 동일하게 할당됨


In [23]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
# iris_df['label'] = iris.target
# iris_df['label'].value_counts()

features = iris.data
label = iris.target

df_clf =DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy=[]

# StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력
for train_index, test_index in skfold.split(features, label):
    #split()으로 반환된 인덱스를 이용해 학습/검증용 테스트 데이터 추출 가능
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 / 예측
    df_clf.fit(x_train, y_train)
    pred = df_clf.predict(x_test)
    
    # 반복 시 마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기 :{2}, 검증 데이터 크기 :{3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
    # 교차 검증별 정확도 및 평균 정확도 계산
    print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
    print('\n## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))
    




#1 교차 검증 정확도 :0.98, 학습 데이터 크기 :100, 검증 데이터 크기 :50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

## 교차 검증별 정확도: [0.98]

## 평균 검증 정확도: 0.98

#2 교차 검증 정확도 :0.94, 학습 데이터 크기 :100, 검증 데이터 크기 :50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

## 교차 검증별 정확도: [0.98 0.94]

## 평균 검증 정확도: 0.96

#3 교차 검증 정확도 :0.98, 학습 데이터 크기 :100, 검증 데이터 크기 :50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]

## 평균 검증 정확도: 0.9667


Stratified KFold의 경우 원본 데이터의 레이블 분포도 특성을 반영한 학습 및 검증 데이터 세트를 만들 수 있음<br>
=> 왜곡된 레이블 데이터 세트에서 Stratified KFold 교차 검증 필요

- 분류(Classfication) : Stratified KFold 교차 검증<br>
- 회귀(Regression) : Stratified KFold 지원 x<br>
    => 회귀 결정값 = 연속된 숫자값이므로 결정값 분포를 정하는 의미가 없음