<h1>scikit-learn</h1>
- 프레임워크, API제공

<h3>3.1 분류 (Classification)</h3>
- 지도학습(Aupervised learning) 방법 중 하나

<h5>** 지도학습</h5>

- 다양한 피처와 분류 결정값인 레이블(Lable) 데이터로 모델을 한습한 후, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측<br>

- 먕확한 정답이 주어진 데이터 先학습， 後 미지의 정답 예측

<h5>사이킷런 모듈</h5>

(1) sklearn.datasets
- 사이킷런 자체 제공 데이터 세트 생성 모듈

(2) sklearn.tree
- 트리기반 ML 알고리즘

(3) sklearn.model_selection
- 학습 데이터, 검증 데이터 통칭
- 하이퍼 파라미터를 통해 머신러닝 알고리즘의 성능 튜닝

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df.head(3)


iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

<h5>▲ Result </h5>

(1) feature
- sepal length
- sepal width
- petal length
- petal width

(2) label
- 0 : Setosa 품종
- 1 : versicolor 품종
- 2 : verginica 품종

<h4>학습용 데이터 및 테스트용 데이터 분리</h4>

- 학습 데이터로 학습된 모델의 성능 평가를 위해 테스트 데이터 세트 필요
- train_test_split()

(1) train_test_split()
- 학습 데이터와 테스트 데이터를 test_size 파라미터 입력값의 비율로 분할


In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)



iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


feature
- iris_data

lable
- iris_lable

test data set 비율
- test_size = 0.2

난수 발생 값 (호출 마다 같은 학습/테스트 용 데이터 세트 생성을 위한)<br>
- random_state

** train_test_split() 호출 시 무작위로 데이터를 분리하므로 random_state() 지정 필요<br>

** DecisionTreeClassifier()
- 의사결정 트리 클래스
- random_state= 지정 
- 학습/예측 결과 출력
- fit() : 학습용 피처 데이터 속성과 결정 값 데이터 세트 입력 


** fit()
- 모델을 학습하는 단계 (피처와 레이블로)

** predict()
- 학습이 끝난 모델이 답을 내는 단계

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris_data : 붓꽃 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris_label : 붓꽃 데이터 세트에서 label(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)

# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(x_train, y_train)

# 학습 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(x_test)

from sklearn.metrics import accuracy_score
print('예측 정확도: {0: 4F}'.format(accuracy_score(y_test, pred)))

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']
예측 정확도:  0.933333


** 정확도 측정

- accuracy_acore()
- 실제 데이터 세트, 예측 레이블 데이터 세트 순으로 입력

** 분류 예측 프로세스

(1) 데이터 세트 분리 : 학습/테스트 데이터 분리<br>
(2) 모델 학습 : 학습 데이터 기반으로 모델 학습<br>
(3) 예측 수행 : 학습된 ML 모델로 테스트 데이터의 분류 예측<br>
(4) 평가 : 예측된 결과값, 테스트 데이터의 실제 결과값 비교 후 모델 성능 평가

<h3>3.2 사이킷런 기반 프레임워크</h3>

<h4>3.2.1 Estimator 이해 및 fit(), predict()</h4>

- fit() : ML 모델 학습
- predict() : 학습된 모델의 예측
- 지도학습 : 분류(Classifier) / 회귀(Regressor) 클래스에서 fit(), predict()으로 간단하게 학습 및 예측 결과 반환 가능
- Estimator 클래스 = 분류(Classifier) + 회귀(Regressor)


- cross_val_score() : evaluation 함수
- GridSearchCV : 파라미터 튜닝
- cross_val_score(), GridSearchCV.fit() : Estimator의 fit(), predict()를 호출해 평가 및 파라미터 튜닝 수행


<h5>** 비지도 학습에서의 fit(), transform() 사용법</h5>

- 비지도학습 : 차원 축소 / 클러스터링 / 피처 추출(Feature Extraction) 
- fit() : 비지도 학습 및 피처 추출에서 fit() 사용시 압력데이터의 형태에 맞춰 데이터를 변환해주기 위해 사전 구조를 맞추는 작업 진행
- transform() : 차원 변환, 클러스터링, 피처 추출 등 실제 작업 진행

- fit_transform() : fit()과 transform()의 결합물<br>
    => fit()과 transform()을 별도로 호출하지 않아도 됨





<h4>3.2.2 사이킷런의 주요 모듈</h4>


<h5>(1) 예제 데이터</h5>

- sklearn.datasets : 내장돤 예제 제공  데이터 세트

<h5>(2) 피처 처리</h5>

- sklearn.preprocessing<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 데이터 전처리에 필요한 가공 기능 (문자열을 숫자형 코드값으로 인코딩, 정규화, 스케일링 등)

- sklearn.feature_selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 일고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행 기능 제공

- sklearn.feature_extraction<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트, 이미지 데이터의 벡터화된 피처를 추출시 사용<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트 데이터 내 Count Vectorizer, TF-IDF Vectorizer 생산 기능 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 텍스트 데이터 피처 추출 : sklearn.feature_extraction.text<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 이미지 데이터 피처 추출 : sklearn.feature_extraction.image<br>

<h5>(3) 피처 처리 & 차원 축소</h5>

- sklearn.decomposition<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 차원 축소 관련 알고리즘 지원 모듈 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> PCA, NMF, Truncated SVD 등을 이용해 차원 축소<br>

<h5>(4) 데이터 분리, 검증 & 파라미터 튜닝</h5>

- sklearn.model_selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 교차 검증을 위한 학습/테스트 용 분리, 그리드 서치로 최적의 파라미터 추출 등 API 제공<br>

<h5>(5) 평가</h5>

- sklearn.metric<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 분류, 회귀, 클러스터링, 페어와이즈(Pairwise)에 대한 다양한 성능 측정 방법<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> Accuracy, Precsion, Recal, ROC-AUC, RMSE 제공<br>

<h5>(6) ML 알고리즘</h5>

- sklearn.ensemble<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 앙상블 알고리즘 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 제공<br>

- sklearn.linear_model<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 선형회귀, 릿지(Ridge), 라쏘(Lasso), 로지스틱 회귀 등 회귀 관련 알고리즘 지원<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> SGD(Stochastic Gradient Descent) 알고리즘 제공<br>

- sklearn.naive_bayes<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 나이브 베이즈 알고리즘 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 기우시안 NB, 다항분포 NB 제공<br>

- sklearn.neighbors<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 최근접 이웃 알고리즘, K-NN<br>

- sklearn.svm<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 서포트 벡터 머신 제공<br>

- sklearn.tree<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 의사결정 트리 제공<br>

- sklearn.cluster<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 비지도 클러스터링 제공<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> K-평균, 계층형, DBSCAN<br>

<h5>(7) 유틸리티</h5>

- sklearn.pipeline<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=> 피처 처리 등 변환, ML 알고리즘 학습, 예측 등을 함께 묶어 실행 가능한 유틸리티 제공<br>

<h4>3.2.3 내장돤 예제 데이터 세트</h4>
- fetch : 데이터 크기가 커 인터넷에서 다운 받아 사용

<h5>** 표본 데이터 생성기</h5>

(1) 분류<br>
- datasets.make_classifications()<br>
    => 분류를 위한 데이터 세트 생성<br>
    => 높은 상관도, 불필요한 속성 등 노이즈 효과를 위한 데이터 무작위로 생성<br>

(2) 클러스터링<br>
- datasets.make_classifications()<br>
    => 클러스터링를 위한 데이터 세트 무작위 생성<br>
    => 군집 지정 개수에 따라 여러 가지 클러스터링을 위한 데이터 무작위로 생성<br>

<h5>** 내장 데이터 구성</h5>
- 딕셔너리 형태<br>
- 키 : data, target, target_name, feature_names, DESCR로 구성<br>

(1) 넘파이 배열(ndarray)<br>
&nbsp;&nbsp;&nbsp;=> data : 피처의 데이터 세트 <br>
&nbsp;&nbsp;&nbsp;=> target : 분류 시 레이블 값 / 회귀 시 숫자 결과값 데이터 세트<br>

(2) 넘파이 배열(ndarray) & 파이썬 list<br>
&nbsp;&nbsp;&nbsp;=> target_name : 개별 레이블 이름<br>
&nbsp;&nbsp;&nbsp;=> feature_names : 피처 명<br>

(3) String 타입<br>
&nbsp;&nbsp;&nbsp;=> DESCR : 데이터 세트 설명 및 각 피처의 설명<br>



In [6]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


** bunch
- 파이썬 딕셔너리 형태와 유사 / 딕셔너리 형태의 값 반환

In [7]:
from sklearn.datasets import load_iris

iris_data = load_iris()
keys = iris_data.keys()

print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [9]:
from sklearn.datasets import load_iris

iris_data = load_iris()
keys = iris_data.keys()

print('\n feature_names의 type:', type(iris_data.feature_names))
print('\n feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('\n target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n data의 type:', type(iris_data.target))
print('data 의 shape:', iris_data.target.shape)
print(iris_data.target)



 feature_names의 type: <class 'list'>

 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>

 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 

<h3>3.3 Model Selection 모듈 소개</h3>

- 학습 / 테스트 데이터 분리
- 교차 검증 분할 및 평가
- Estimator의 하이퍼 파라미터 튜닝

<h4>3.3.1 학습/테스트 데이터 분리 - train_test_split()</h4>

In [10]:
# 학습과 예측을 동일 데이터 세트로 진행 예제

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
df_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
df_clf.fit(train_data, train_label)

# 학습 데이터 세트로 예측 수행
pred = df_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0
